# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  codecov: codecov/codecov@3.0.0

commands:
  setup-dependencies:
    steps:
      - run: apt-get -y update &&
          apt-get -y install
          curl gcc-10 git cmake
jobs:
  build_test_bench:
    docker:
      - image: ubuntu:20.04
    environment:
      DEBIAN_FRONTEND: noninteractive
    steps:
      - setup-dependencies
      - checkout
      - run: |
          mkdir build && cd build
          cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=1 -DFILTERS_TEST=1 -DCMAKE_BUILD_TYPE=Debug ..
          cmake --build .
          ./blocked_bloom_filter_test
          ./bloom_filter_test
      - run: |
          mkdir build_bench && cd build_bench
          cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=1 -DFILTERS_BENCH=1 -DCMAKE_BUILD_TYPE=Debug ..
          cmake --build .
          ./blocked_bloom_filter_bench
          ./bloom_filter_bench

# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "run"
  run:
    jobs:
      - build_test_bench
